### ISSUE TITLE
3.0.0b6: country=cn -> invalid org (1202)

### ISSUE THREAD

**Issue by Crazysiri** [And3rsL/Deebot-for-Home-Assistant#139]
**Describe the bug**
steps:
1.setup integration via the UI.
2.select 'Bumper' 
3.select 'Submit'
4.it shows 'unkown error' on the UI.

** Logs **
1.
Logger: deebotozmo.ecovacs_api
Source: /usr/local/lib/python3.8/site-packages/deebotozmo/ecovacs_api.py:170 
First occurred: 7:07:07 PM (3 occurrences) 
Last logged: 7:20:29 PM
* call to https://gl-it-api.ecovacs.com/v1/private/it/EN/O06DNAS9/global_e/1.6.3/google_play/1/user/login failed with {'code': '1010', 'msg': 'Incorrect account or password', 'time': 1624014426985, 'data': None, 'success': False}

2.
Logger: custom_components.deebot.config_flow
Source: custom_components/deebot/config_flow.py:55 
Integration: Deebot for Home Assistant (documentation, issues) 
First occurred: 7:07:07 PM (3 occurrences) 
Last logged: 7:20:29 PM
Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/deebot/config_flow.py", line 69, in async_step_user
    info = await self.async_retrieve_bots(user_input)
  File "/config/custom_components/deebot/config_flow.py", line 55, in async_retrieve_bots
    await ecovacs_api.login()
  File "/usr/local/lib/python3.8/site-packages/deebotozmo/ecovacs_api.py", line 64, in login
    login_info = await self.__call_login_api(self.account_id, self._password_hash)
  File "/usr/local/lib/python3.8/site-packages/deebotozmo/ecovacs_api.py", line 183, in __call_login_api
    return await self.__do_auth_response(url, self.__sign(params))
  File "/usr/local/lib/python3.8/site-packages/deebotozmo/ecovacs_api.py", line 171, in __do_auth_response
    raise RuntimeError(f"failure code {json['code']} ({json['msg']}) for call {url}")
RuntimeError: failure code 1010 (Incorrect account or password) for call https://gl-it-api.ecovacs.com/v1/private/it/EN/O06DNAS9/global_e/1.6.3/google_play/1/user/login

It seems login with incorrect account or password. but I didn't input any account or password at that step.
It also happens when I select cloud(recommended);

**Comment by edenhaus** [comment]
You can select only the option „Bumper“ if you have a working instance of it running. So is your bumper instance working correctly?

**Comment by Crazysiri** [comment]
1. It is working correctly on the version 2.1.2.
2. I removed the integration after I upgraded it to 3.0 then I tried to reinstall it.
3. here is the error logs for the 'cloud' option:
   1) Logger: deebotozmo.ecovacs_api
       Source: /usr/local/lib/python3.8/site-packages/deebotozmo/ecovacs_api.py:253 
       First occurred: 7:06:46 PM (3 occurrences) 
       Last logged: 8:39:14 PM
       call to users/user.do failed with {'todo': 'result', 'result': 'fail', 'errno': 1202, 'error': 'invalid org'}  
   2)Logger: custom_components.deebot.config_flow
       Source: custom_components/deebot/config_flow.py:55 
       Integration: Deebot for Home Assistant (documentation, issues) 
       First occurred: 7:06:46 PM (3 occurrences)  
       Last logged: 8:39:14 PM 
       Unexpected exception
       Traceback (most recent call last):
         File "/config/custom_components/deebot/config_flow.py", line 69, in async_step_user
            info = await self.async_retrieve_bots(user_input)
         File "/config/custom_components/deebot/config_flow.py", line 55, in async_retrieve_bots
            await ecovacs_api.login()
         File "/usr/local/lib/python3.8/site-packages/deebotozmo/ecovacs_api.py", line 69, in login
            login_response = await self.__call_login_by_it_token(user_id, auth_code)
         File "/usr/local/lib/python3.8/site-packages/deebotozmo/ecovacs_api.py", line 254, in __call_login_by_it_token
            raise RuntimeError(
      RuntimeError: failure invalid org (1202) for call users/user.do and parameters {'edition': 'ECOGLOBLE', 'userId': 'xxx', 'token': 'xxx', 'realm': 'ecouser.net', 'resource': 'O06DNAS9', 'org': 'ECOCN', 'last': '', 'country': 'Chinese', 'todo': 'loginByItToken'}

**Comment by edenhaus** [comment]
I released a new beta. 
@Crazysiri  @cloudicen Can you please try it and give me feedback if the bug is resolved?

**Comment by cloudicen** [comment]
I've tried. And the same error code occurs:  invalid org (1202).

**Comment by edenhaus** [comment]
OK probably I have forgotten something... I give it a look later

**Comment by edenhaus** [comment]
@cloudicen Can you please retry with beta 8?

**Comment by cloudicen** [comment]
The frontend shows: "Retrying setup: Error during setup".
But "Deebotozmo api" seems working perfectly?

Here are logs:

 2021-07-04 02:10:30 INFO (MainThread) [custom_components.deebot]

-------------------------------------------------------------------

deebot

Version: 3.0.0b8

This is a custom component

If you have any issues with this you need to open an issue here:

https://github.com/And3rsL/Deebot-for-Home-Assistant/issues

-------------------------------------------------------------------

2021-07-04 02:10:30 DEBUG (MainThread) [deebotozmo.ecovacs_api] Start login to EcovacsAPI

2021-07-04 02:10:30 DEBUG (MainThread) [deebotozmo.ecovacs_api] calling login api

2021-07-04 02:10:31 DEBUG (MainThread) [deebotozmo.ecovacs_api] got {'code': '0000', 'msg': '操作成功', 'time': 1625335831172, 'data': {'uid': '####', 'accessToken': '####', 'userName': '##', 'email': None, 'mobile': '####', 'isNew': None, 'loginName': '####', 'ucUid': '####', 'hasMobile': 'Y', 'isNewThirdAccount': None}, 'success': True}

2021-07-04 02:10:31 DEBUG (MainThread) [deebotozmo.ecovacs_api] calling auth api

2021-07-04 02:10:36

**Comment by cloudicen** [comment]
2021-07-04 02:10:30 INFO (MainThread) [custom_components.deebot]

-------------------------------------------------------------------

deebot

Version: 3.0.0b8

This is a custom component

If you have any issues with this you need to open an issue here:

https://github.com/And3rsL/Deebot-for-Home-Assistant/issues

-------------------------------------------------------------------

2021-07-04 02:10:30 DEBUG (MainThread) [deebotozmo.ecovacs_api] Start login to EcovacsAPI

2021-07-04 02:10:30 DEBUG (MainThread) [deebotozmo.ecovacs_api] calling login api

2021-07-04 02:10:31 DEBUG (MainThread) [deebotozmo.ecovacs_api] got {'code': '0000', 'msg': '操作成功', 'time': 1625335831172, 'data': {'uid': '####', 'accessToken': '####', 'userName': '##', 'email': None, 'mobile': '####', 'isNew': None, 'loginName': '####', 'ucUid': '####', 'hasMobile': 'Y', 'isNewThirdAccount': None}, 'success': True}

2021-07-04 02:10:31 DEBUG (MainThread) [deebotozmo.ecovacs_api] calling auth api

2021-07-04 02:10:36 DEBUG (MainThread) [deebotozmo.ecovacs_api] got {'code': '0000', 'msg': '操作成功', 'time': 1625335831269, 'data': {'authCode': '####', 'ecovacsUid': '####'}, 'success': True}

2021-07-04 02:10:36 DEBUG (MainThread) [deebotozmo.ecovacs_api] calling user api users/user.do with {'edition': 'ECOGLOBLE', 'userId': '####', 'token': '####', 'realm': 'ecouser.net', 'resource': '####', 'org': 'ECOCN', 'last': '', 'country': 'Chinese', 'todo': 'loginByItToken'}

2021-07-04 02:10:37 DEBUG (MainThread) [deebotozmo.ecovacs_api] got {'todo': 'result', 'result': 'ok', 'userId': '####', 'resource': '####', 'token': '####', 'last': 604800000}

2021-07-04 02:10:37 DEBUG (MainThread) [deebotozmo.ecovacs_api] Switching to shorter UID ####

2021-07-04 02:10:37 DEBUG (MainThread) [deebotozmo.ecovacs_api] Login to EcovacsAPI successfully

2021-07-04 02:10:37 DEBUG (MainThread) [deebotozmo.ecovacs_api] calling user api appsvr/app.do with {'userid': '####', 'auth': {'with': 'users', 'userid': '####', 'realm': 'ecouser.net', 'token': '####'}, 'todo': 'GetGlobalDeviceList'}

2021-07-04 02:10:39 DEBUG (MainThread) [deebotozmo.ecovacs_api] got {'code': 0, 'todo': 'result', 'ret': 'ok', 'devices': [{'did': '####', 'name': '####', 'class': '####', 'resource': '####', 'nick': None, 'company': 'eco-ng', 'bindTs': ####, 'service': {'jmq': 'jmq-ngiot-cn.dc.cn.ecouser.net', 'mqs': 'api-ngiot.dc-cn.cn.ecouser.net'}, 'deviceName': 'DEEBOT T5 Power', 'icon': 'https://portal.ecouser.net/api/pim/file/get/####', 'ota': True, 'UILogicId': '####', 'materialNo': '####', 'pid': '####', 'product_category': 'DEEBOT', 'model': 'DX93S', 'updateInfo': {'needUpdate': False, 'changeLog': ''}, 'status': 1, 'offmap': True}]}

2021-07-04 02:10:39 DEBUG (MainThread) [deebotozmo.ecovacs_json] Calling https://portal.ecouser.net/api//iot/devmanager.do?#### with {'auth': {'with': 'users', 'userid': '####', 'realm': 'ecouser.net', 'token': '####', 'resource': '####'}, 'cmdName': 'getChargeState', 'payload': {'header': {'pri': '1', 'ts': 1625335839.485095, 'tzm': 480, 'ver': '0.0.50'}}, 'payloadType': 'j', 'td': 'q', 'toId': '####', 'toRes': 'Q70a', 'toType': '1zbh67'}

2021-07-04 02:10:39 DEBUG (MainThread) [deebotozmo.ecovacs_json] Calling https://portal.ecouser.net/api//iot/devmanager.do?#### with {'auth': {'with': 'users', 'userid': 'e#e#', 'realm': 'ecouser.net', 'token': '####'}, 'cmdName': 'getCleanInfo', 'payload': {'header': {'pri': '1', 'ts': 1625335839.501849, 'tzm': 480, 'ver': '0.0.50'}}, 'payloadType': 'j', 'td': 'q', 'toId': '####', 'toRes': 'Q70a', 'toType': '1zbh67'}

2021-07-04 02:10:40 DEBUG (MainThread) [deebotozmo.ecovacs_json] Got {'ret': 'ok', 'resp': {'header': {'pri': 1, 'tzm': 480, 'ts': '1625335837557', 'ver': '0.0.1', 'fwVer': '1.2.1', 'hwVer': '0.1.1'}, 'body': {'code': 0, 'msg': 'ok', 'data': {'isCharging': 1, 'mode': 'slot'}}}, 'id': 'dKD1'}

2021-07-04 02:10:40 DEBUG (MainThread) [deebotozmo.vacuum_bot] Handle getChargeState: {'ret': 'ok', 'resp': {'header': {'pri': 1, 'tzm': 480, 'ts': '1625335837557', 'ver': '0.0.1', 'fwVer': '1.2.1', 'hwVer': '0.1.1'}, 'body': {'code': 0, 'msg': 'ok', 'data': {'isCharging': 1, 'mode': 'slot'}}}, 'id': 'dKD1'}

2021-07-04 02:10:40 DEBUG (MainThread) [deebotozmo.events] Notify subscribers with StatusEvent(available=True, state=<VacuumState.STATE_DOCKED: 4>)

2021-07-04 02:10:40 DEBUG (MainThread) [deebotozmo.ecovacs_json] Got {'ret': 'ok', 'resp': {'header': {'pri': 1, 'tzm': 480, 'ts': '1625335837572', 'ver': '0.0.1', 'fwVer': '1.2.1', 'hwVer': '0.1.1'}, 'body': {'data': {'trigger': 'workComplete', 'state': 'idle'}, 'code': 0, 'msg': 'ok'}}, 'id': 'Xqn6'}

2021-07-04 02:10:40 DEBUG (MainThread) [deebotozmo.vacuum_bot] Handle getCleanInfo: {'ret': 'ok', 'resp': {'header': {'pri': 1, 'tzm': 480, 'ts': '1625335837572', 'ver': '0.0.1', 'fwVer': '1.2.1', 'hwVer': '0.1.1'}, 'body': {'data': {'trigger': 'workComplete', 'state': 'idle'}, 'code': 0, 'msg': 'ok'}}, 'id': 'Xqn6'}

**Comment by edenhaus** [comment]
@cloudicen from your logs the component works correctly. If you get still an error then please provide us with more logs and stacktraces, Probably you have delete out some relevant logs. If the issue still exist please create a new issue with the appropriate logs. There must be some warnings or errors in your logs.

Closing this issue as it is resolved

**Comment by Crazysiri** [comment]
it is so strange that I have tried with beta 8 but there is no error logs except for this:
"2021-07-04 09:16:18 DEBUG (MainThread) [homeassistant.config_entries] Config entry 'xxx' for deebot integration not ready yet: Error during setup; Retrying in 80 seconds" 

and a screenshot:

<img width="503" alt="截屏2021-07-04 下午5 19 08" src="https://user-images.githubusercontent.com/7479347/124379889-44d2f280-dcec-11eb-8fd8-f39284515620.png">

should I start with a new issue?
