### ISSUE TITLE
KeyError: 'nick'

### ISSUE THREAD

**Issue by mx4k** [And3rsL/Deebot-for-Home-Assistant#152]
**Describe the bug**
II can't login into my account due to an 'unknown error'

**System Informations:**
 - Device: Deebot OZMO T8 AIVI
 - Home Assistant Version: 2021.7.0
 - Hardware: Raspberry Pi4
 - Home Assistant Installation: Home Assistant OS 6.1

**Logs**
```
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 155, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 202, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/deebot/config_flow.py", line 85, in async_step_user
    robot_listDict = {e["name"]: e["nick"] for e in self.robot_list}
  File "/config/custom_components/deebot/config_flow.py", line 85, in <dictcomp>
    robot_listDict = {e["name"]: e["nick"] for e in self.robot_list}
KeyError: 'nick'
```

**Comment by mx4k** [comment]
This appears when you don't have a nickname set in your Ecovacs account.
