### ISSUE TITLE
Suddenly the integration stopped working for one of my account

### ISSUE THREAD

**Issue by Edo78** [And3rsL/Deebot-for-Home-Assistant#157]
**Describe the bug**
I have two bots on two different accounts. One of those account is a chinese one and it suddenly not working anymore (the app is still working).

**System Informations:**
 - Device: Deebot OZMO T8+ AIVI
 - Home Assistant Version: 2021.7.3
 - Hardware: Raspberry Pi 4
 - Home Assistant Installation: Docker

**Additional context**
I'm on the latest stable integration 2.1.2

**Logs**
```
2021-07-19 16:31:02 DEBUG (SyncWorker_5) [deebotozmo] got {'code': '****', 'msg': '****', 'time': 1626705062571, 'data': {'uid': '*********************', 'accessToken': '*************', 'userName': '********', 'email': None, 'mobile': '+86-**********', 'isNew': None, 'loginName': '**********', 'ucUid': '****************', 'hasMobile': 'Y', 'isNewThirdAccount': None}, 'success': True}
2021-07-19 16:31:02 DEBUG (SyncWorker_5) [deebotozmo] calling auth api with (('uid', '*********************'), ('accessToken', '*************'))
2021-07-19 16:31:06 DEBUG (SyncWorker_0) [deebotozmo] got {'code': '****', 'msg': '****', 'time': 1626705066300, 'data': {'authCode': '****************', 'ecovacsUid': '20210126124954_0e3b817c637b4c26a918b1fe30225505'}, 'success': True}
2021-07-19 16:31:06 DEBUG (SyncWorker_0) [deebotozmo] calling user api loginByItToken with {'edition': 'ECOGLOBLE', 'userId': '****************', 'token': '****************', 'realm': 'ecouser.net', 'resource': 'MJ8CPYAG', 'org': 'ECOWW', 'last': '', 'country': 'IT'}
2021-07-19 16:31:07 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Attila for deebot
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
self._validate_conn(conn)
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
conn.connect()
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
self.sock = ssl_wrap_socket(
File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
ssl_sock = _ssl_wrap_socket_impl(
File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
return self.sslsocket_class._create(
File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
self.do_handshake()
File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
raise value.with_traceback(tb)
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
self._validate_conn(conn)
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
conn.connect()
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
self.sock = ssl_wrap_socket(
File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
ssl_sock = _ssl_wrap_socket_impl(
File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
return self.sslsocket_class._create(
File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
self.do_handshake()
File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/deebot/__init__.py", line 30, in async_setup_entry
hass.data[DOMAIN][entry.entry_id] = await hass.async_add_executor_job(
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/deebot/hub.py", line 30, in __init__
self.ecovacs_api = EcoVacsAPI(
File "/usr/local/lib/python3.9/site-packages/deebotozmo/__init__.py", line 74, in __init__
self.auth_code = self.__call_auth_api(
File "/usr/local/lib/python3.9/site-packages/deebotozmo/__init__.py", line 166, in __call_auth_api
api_response = requests.get(
File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 76, in get
return request('get', url, params=params, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by Edo78** [comment]
It must be a server side issue ... the 5 HA restart was able to have it working again.
Is there any way, other then restarting the whola HA, to restart just the integration in case this happen again?

**Comment by edenhaus** [comment]
From the issue I know, that there are currently some issue for Chinese users.

> Is there any way, other then restarting the whola HA, to restart just the integration in case this happen again?

Have you tried the reload mechanism from HA? Can be found if you click on the dots-button in the integration view

**Comment by Edo78** [comment]
> Have you tried the reload mechanism from HA? Can be found if you click on the dots-button in the integration view
it seems to work but right now there are other issue with the server
