### ISSUE TITLE
"Setup failed for deebot: No setup function defined" on startup

### ISSUE THREAD

**Issue by Smilebags** [And3rsL/Deebot-for-Home-Assistant#169]
**Describe the bug**
```
2021-08-01 22:26:04 ERROR (MainThread) [homeassistant.setup] Setup failed for deebot: No setup function defined.
```

**System Informations:**
 - Deebot for Home Assistant v3.0.1
 - Device: Deebot ozmo T8
 - Home Assistant 2021.3.4
 - Hardware: Raspberry Pi
 - Home Assistant Installation: Docker on Raspian

**Additional context**
Running the setup successfully showed the device dropdown with a single entity, so it seems like it was able to connect properly initially. The entity isn't showing up in HA, and I'm getting the above error on startup.

**Logs**
These are the entire logs in `homeassistant.log`
```
2021-08-01 22:26:02 WARNING (MainThread) [homeassistant.loader] You are using a custom integration deebot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-08-01 22:26:02 WARNING (MainThread) [homeassistant.loader] You are using a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-08-01 22:26:02 WARNING (MainThread) [homeassistant.loader] You are using a custom integration ble_monitor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-08-01 22:26:04 ERROR (MainThread) [homeassistant.setup] Setup failed for deebot: No setup function defined.
2021-08-01 22:27:16 DEBUG (MainThread) [homeassistant.components.webhook] Handling webhook POST payload for ********
2021-08-01 22:29:54 DEBUG (MainThread) [homeassistant.components.webhook] Handling webhook POST payload for ********
2021-08-01 22:29:55 DEBUG (MainThread) [homeassistant.components.webhook] Handling webhook POST payload for ********
2021-08-01 22:29:59 ERROR (MainThread) [homeassistant.components.system_health] Error fetching system info for cloud - can_reach_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/system_health/__init__.py", line 212, in async_check_can_reach_url
    await session.get(url, timeout=5)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
2021-08-01 22:30:21 DEBUG (MainThread) [homeassistant.components.webhook] Handling webhook POST payload for ********
2021-08-01 22:31:22 DEBUG (MainThread) [homeassistant.components.webhook] Handling webhook POST payload for ********
2021-08-01 22:31:22 DEBUG (MainThread) [homeassistant.components.webhook] Handling webhook POST payload for ********
2021-08-01 22:31:22 DEBUG (MainThread) [homeassistant.components.webhook] Handling webhook POST payload for ********
2021-08-01 22:31:23 DEBUG (MainThread) [homeassistant.components.webhook] Handling webhook POST payload for ********
```

It really doesn't seem like it's getting very far with the setup.

**Comment by edenhaus** [comment]
Can you please try to update HA to the latest version (2021.7.4)?
Not sure if something has changed but it sounds like.

**Comment by Smilebags** [comment]
That worked, thanks. HA was having problems after upgrading but once I sorted them out this started working.
