### ISSUE TITLE
 DEEBOT T8 AIVI connect Home Assistant issue

### ISSUE THREAD

**Issue by longdaokm** [And3rsL/Deebot-for-Home-Assistant#173]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Hello,

I follow below procedures to integrate Deebot T8 Aivi to Home Assistant: 
- Install Home Assistant OS - running Virtualbox VM
- Install HACS 
- Add Deebot for Home Assistant v3.0.2 to repository
- Add Deebot T8 AIVI mainland China in Configuration -> Intergrations: username ECXUPxxx, country CN, Continent WW

has error: Retrying setup: Error during setup

Check log as below:

### On which deebot vacuum you have the issue?

Deebot T8 AIVI Mainland China

### Which version of the Deebot component are you using?

3.0.2

### Which version of Home Assistant are you using?

2021.7.4

### What type of installation are you running?

Home Assistant OS

### Country

cn

### Continent

as

### Instance type

Cloud

### Anything in the logs that might be useful for us?

```
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
return await self._loop.create_connection(*args, **kwargs) # type: ignore # noqa
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1081, in create_connection
transport, protocol = await self._create_connection_transport(
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1111, in _create_connection_transport
await waiter
ConnectionAbortedError: SSL handshake is taking longer than 60.0 seconds: aborting the connection
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/deebotozmo/events.py", line 146, in _call_refresh_function
await self._refresh_function()
File "/usr/local/lib/python3.9/site-packages/deebotozmo/util.py", line 42, in refresh
await asyncio.gather(*tasks)
File "/usr/local/lib/python3.9/site-packages/deebotozmo/vacuum_bot.py", line 84, in execute_command
response = await self.json.send_command(command, self.vacuum)
File "/usr/local/lib/python3.9/site-packages/deebotozmo/ecovacs_json.py", line 38, in send_command
async with self._session.post(
File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
self._resp = await self._coro
File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
conn = await self._connector.connect(
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
proto = await self._create_connection(req, traces, timeout)
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
_, proto = await self._create_direct_connection(req, traces, timeout)
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
raise last_exc
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
transp, proto = await self._wrap_create_connection(
File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host portal.ecouser.net:443 ssl:True [None
```

**Comment by edenhaus** [comment]
Your issue is inconsistent. Above you write, that you setup with continent `ww` and below you specify `as`.
Also there exists two already some issue for the T8 (#153. #154,...) Please check them out first

From the error, it looks like your HA-instance cannot connect to `portal.ecouser.net`, do you have a stable internet connection?

**Comment by Yterz** [comment]
It look like the error I got as well with the new update 3.0.x, it's not working properly with China Mainland.

Try deleting you config, then reinstall the integration, but with version 2.1.2 (you can pick that with HACS at the reinstall screen), and reconfigure :


("as" or "ww" doesn't matter when country = "cn" if I understood properly, it's a whole different server anyway)

**Comment by longdaokm** [comment]
Just able to select version 3.0.0.b12 as below.
How can I install 2.1.2?

![image](https://user-images.githubusercontent.com/51350418/128464710-c8577e34-2939-45ed-94fa-c2b0fd3169b0.png)

**Comment by longdaokm** [comment]
It's working now. Many thanks everyone!
