### ISSUE TITLE
Error after integration setup

### ISSUE THREAD

**Issue by vincenzocalabrese** [And3rsL/Deebot-for-Home-Assistant#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Hello,
after component upgrade (from 2.1.2 to 3.1.0) I've some problem to use the integration.
I've removed and recreated the configuration and selected the correct deebot proposed by the form, but after that, I've this error.
![image](https://user-images.githubusercontent.com/30824836/129012249-34186a02-da4d-4e4d-a80a-ed2ffe0038af.png)

Thanks for your help,
Vincenzo

### On which deebot vacuum you have the issue?

Deebot Ozmo 920

### Which version of the Deebot component are you using?

3.1.0

### Which version of Home Assistant are you using?

2021.8.4

### What type of installation are you running?

Home Assistant Container

### Country

it

### Continent

eu

### Instance type

Cloud

### Anything in the logs that might be useful for us?

```txt
--- Logging error ---
Traceback (most recent call last):
  File "/config/custom_components/deebot/hub.py", line 81, in async_setup
    await self._mqtt.subscribe(vacbot)
  File "/usr/local/lib/python3.9/site-packages/deebotozmo/ecovacs_mqtt.py", line 64, in subscribe
    await self.initialize()
  File "/usr/local/lib/python3.9/site-packages/deebotozmo/ecovacs_mqtt.py", line 60, in initialize
    await self._client.connect(self._hostname, self._port, ssl=ssl_ctx, version=MQTTv311)
  File "/usr/local/lib/python3.9/site-packages/gmqtt/client.py", line 160, in connect
    self._connection = await self._create_connection(
  File "/usr/local/lib/python3.9/site-packages/gmqtt/client.py", line 178, in _create_connection
    connection = await MQTTConnection.create_connection(host, port, ssl, clean_session, keepalive)
  File "/usr/local/lib/python3.9/site-packages/gmqtt/mqtt/connection.py", line 27, in create_connection
    transport, protocol = await loop.create_connection(MQTTProtocol, host, port, ssl=ssl)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1017, in create_connection
    infos = await self._ensure_resolved(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1396, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1431, in emit
    self.enqueue(self.prepare(record))
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1414, in prepare
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/config/custom_components/deebot/__init__.py", line 26, in async_setup_entry
    await deebot_hub.async_setup()
  File "/config/custom_components/deebot/hub.py", line 90, in async_setup
    _LOGGER.error(msg, e, exc_info=True)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/src/homeassistant/homeassistant/util/logging.py", line 51, in handle
    self.emit(record)
Message: 'Error during setup'
Arguments: (gaierror(-2, 'Name does not resolve'),)
```

**Comment by edenhaus** [comment]
Do you have a stable internet connection?
The url cannot be resolved so... Dou you have a DNS Adblock oder a custom dns server running?

**Comment by vincenzocalabrese** [comment]
Hello edenhaus,
yes! I've a good internet connection.
I haven't any custom DNS or adblock systems.
I've downgraded the package to version 2.1.2 and still work.
The configurations data are not changed after downgrade.

Can you send me the endpoint name? In this way I can test the resolution thorugh my PC.
Otherwise, tell me please how to retrieve that information in the source code.
I check the URL and send to you a feedback

Thanks!!
Vincenzo

**Comment by edenhaus** [comment]
MQTT tries to connect to `mq-eu.ecouser.net` if your configuration values above are correct

**Comment by vincenzocalabrese** [comment]
Hello,
the endpoint is reacheable from my network.

I've resolved the issue. in the follow list the tasks performed to resolve:
- remove entities
- remove device
- package disinstallation
- home assistant cache cleaning
- package installation

And now all work fine.

Thanks for your support,
Vincenzo
