### ISSUE TITLE
Multi-floor issue

### ISSUE THREAD

**Issue by marioedani** [And3rsL/Deebot-for-Home-Assistant#183]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Hi. Some time ago I opened this issue: (https://github.com/And3rsL/Deebot-for-Home-Assistant/issues/72#issue-782354518)
It has been solved, but now, with latest relases, when I move to the other floor of my house, room attributes don't change accordingly.
The only way I found being successfull to update rooms list is to make a complete clean of at leasr one room, using android app; then, when robot comes back to the docking station, rooms list finally changes.

When does rooms list update?
Can you update it every time vacuum state changes to "docked"?
Or is there a way to update it "manually"?

Thank you

### On which deebot vacuum you have the issue?

Deebot Ozmo 920

### Which version of the Deebot component are you using?

3.1.0

### Which version of Home Assistant are you using?

2021.8.6

### What type of installation are you running?

Home Assistant OS

### Country

it

### Continent

eu

### Instance type

Cloud

**Comment by marioedani** [comment]
> The rooms will update, when the robot send them out. In v3 we don't poll the information instead we listen on event from the robot.

I waited more than 1 hour after I moved the robot to the new location (the second floor), but rooms list did not update. On the contrary, Ecovacs android app changed map correctly.

> I don't know exactly, when the robot sends out the room event, but you can use the service `deebot.refresh` with part set to rooms, to manually refresh the rooms.

I tried to call the `deebot.refresh` service but i got an error:

`2021-08-30 19:49:27 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2021-08-30 19:49:27 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2021-08-30 19:49:27 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: no running event loop
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 665, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 856, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
await result
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/deebot/vacuum.py", line 248, in _service_refresh
self._device.statusEvents.request_refresh()
File "/usr/local/lib/python3.9/site-packages/deebotozmo/events.py", line 150, in request_refresh
asyncio.create_task(self._call_refresh_function())
File "/usr/local/lib/python3.9/asyncio/tasks.py", line 360, in create_task
loop = events.get_running_loop()
RuntimeError: no running event loop
2021-08-30 19:49:27 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1626317368] Error handling message: Unknown error
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 525, in handle_execute_script
await script_obj.async_run(msg.get("variables"), context=context)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1219, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 353, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 665, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 856, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
await result
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/deebot/vacuum.py", line 248, in _service_refresh
self._device.statusEvents.request_refresh()
File "/usr/local/lib/python3.9/site-packages/deebotozmo/events.py", line 150, in request_refresh
asyncio.create_task(self._call_refresh_function())
File "/usr/local/lib/python3.9/asyncio/tasks.py", line 360, in create_task
loop = events.get_running_loop()
RuntimeError: no running event loop
`

The only way to update rooms list is to reload Deebot integration. This wasn't necessary with the older versions of the component.

Thank you for your help

**Comment by edenhaus** [comment]
I will check the error in the next days.

The ecovacs app and version below 3 of this component are using polling to get the information. In version 2 we polled all information each 5-30 seconds, which the most of the time was useless as the didn‘t change, but on the other hand produced a lot of network traffic.

In version 3 and ongoing we are listing for updates from the robot. As we don‘t control the firmware, we cannot specify, when the robot sends out the information.

**Comment by edenhaus** [comment]
Can you please try `3.1.2b1` and tell me if the service problem is fixed?

**Comment by marioedani** [comment]
Sorry I've seen your message now. I tried the `deebot.refresh` service and now it works correctly. Non more need to reload integration. This is good. Thank you.

But, still, rooms list does not update automatically.

**Comment by edenhaus** [comment]
> But, still, rooms list does not update automatically.

The robot is not sending out an event that the rooms have changed. As mentioned earlier, we do not poll anymore data each 5-30s as most off the time the data is not changed! The app is pulling all information when you open it.

Feel free to investigate the logs (see [logs](https://github.com/And3rsL/Deebot-for-Home-Assistant/blob/master/README.md#issues)), maybe there is something, where we can recognize that the robot was moved to another floor.

**Comment by edenhaus** [comment]
As I use my vacuum only on one floor, I don‘t can investigate it. Please feel free to provide logs or even better analyse it 😊
