### ISSUE TITLE
2021.9 Error live map: "integer argument expected, got float"

### ISSUE THREAD

**Issue by snakuzzo** [And3rsL/Deebot-for-Home-Assistant#187]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

If I add this card to show live map, every time I switch to dashboard that contains that card, on Core logs I see errors

### On which deebot vacuum you have the issue?

Deebot Ozmo N8 Pro +

### Which version of the Deebot component are you using?

3.1.1

### Which version of Home Assistant are you using?

2021.9.0

### What type of installation are you running?

Home Assistant Container

### Country

it

### Continent

eu

### Instance type

Cloud

### Anything in the logs that might be useful for us?

```txt
2021-09-02 00:10:26 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 211, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 590, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 608, in handle
    image = await _async_get_image(
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 164, in _async_get_image
    image_bytes = await camera.async_camera_image(
  File "/config/custom_components/deebot/camera.py", line 57, in async_camera_image
    return base64.decodebytes(self._vacuum_bot.map.get_base64_map(width))
  File "/usr/local/lib/python3.9/site-packages/deebotozmo/map.py", line 371, in get_base64_map
    cropped = cropped.resize((cropped.size[0] * resize_factor, cropped.size[1] * resize_factor), Image.NEAREST)
  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 1943, in resize
    return self._new(self.im.resize(size, resample, box))
TypeError: integer argument expected, got float
```
```


### Additional information

_No response_

**Comment by Scialla** [comment]
Same problem here with Last HA core in Venv

**Comment by edenhaus** [comment]
Can you please try `3.1.2b1` and tell me if the problem is fixed?

**Comment by snakuzzo** [comment]
It's ok now. No errors and live map is ok.

Thanks

**Comment by edenhaus** [comment]
Please leave it open, it will be closed, when a new version is released

**Comment by snakuzzo** [comment]
Some errors while deebot was cleaning...

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deebotozmo/ecovacs_mqtt.py", line 48, in _on_message
    await bot.handle(topic_split[2], data, False)
  File "/usr/local/lib/python3.9/site-packages/deebotozmo/vacuum_bot.py", line 189, in handle
    await self._map.handle(event_name, event_data, requested)
  File "/usr/local/lib/python3.9/site-packages/deebotozmo/map.py", line 118, in handle
    self._handle_map_sub_set(event_data)
  File "/usr/local/lib/python3.9/site-packages/deebotozmo/map.py", line 173, in _handle_map_sub_set
    subtype = int(event_data["subtype"])
KeyError: 'subtype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1431, in emit
    self.enqueue(self.prepare(record))
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1414, in prepare
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 322, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 314, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 108, in run
    return asyncio.run(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/site-packages/deebotozmo/ecovacs_mqtt.py", line 51, in _on_message
    _LOGGER.error("An exception occurred", err, exc_info=True)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/src/homeassistant/homeassistant/util/logging.py", line 51, in handle
    self.emit(record)
Message: 'An exception occurred'
Arguments: (KeyError('subtype'),)
--- Logging error ---
2021-09-02 10:59:14 ERROR (Thread-2) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1517, in _monitor
    self.handle(record)
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1498, in handle
    handler.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 192, in emit
    entry = LogEntry(record, stack, _figure_out_source(record, stack, self.hass))
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 99, in __init__
    self.message = deque([record.getMessage()], maxlen=5)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deebotozmo/ecovacs_mqtt.py", line 48, in _on_message
    await bot.handle(topic_split[2], data, False)
  File "/usr/local/lib/python3.9/site-packages/deebotozmo/vacuum_bot.py", line 189, in handle
    await self._map.handle(event_name, event_data, requested)
  File "/usr/local/lib/python3.9/site-packages/deebotozmo/map.py", line 118, in handle
    self._handle_map_sub_set(event_data)
  File "/usr/local/lib/python3.9/site-packages/deebotozmo/map.py", line 173, in _handle_map_sub_set
    subtype = int(event_data["subtype"])
KeyError: 'subtype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1431, in emit
    self.enqueue(self.prepare(record))
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1414, in prepare
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 322, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 314, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 108, in run
    return asyncio.run(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/site-packages/deebotozmo/ecovacs_mqtt.py", line 51, in _on_message
    _LOGGER.error("An exception occurred", err, exc_info=True)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/src/homeassistant/homeassistant/util/logging.py", line 51, in handle
    self.emit(record)
Message: 'An exception occurred'
Arguments: (KeyError('subtype'),)
2021-09-02 11:00:30 WARNING (MainThread) [deebotozmo.vacuum_bot] Invalid Event cleanlogs: {}
2021-09-02 11:07:47 ERROR (MainThread) [deebotozmo.ecovacs_api] call to appsvr/app.do failed with {'todo': 'result', 'ret': 'fail', 'errno': 3002, 'code': 3002}
2021-09-02 11:07:47 ERROR (MainThread) [custom_components.deebot.hub] Unknown exception occurred: 'error'
```
