### ISSUE TITLE
Deebot OZMO Slim 10

### ISSUE THREAD

**Issue by h4de5** [And3rsL/Deebot-for-Home-Assistant#76]
**Describe the bug**
Vacuum is listed with the correct name, but marked as unavailable all the time. 
cannot be started.

I tried today all available ecovacs libraries - non worked so far:
https://www.home-assistant.io/integrations/ecovacs/
https://github.com/Ligio/hacc-ozmo
https://github.com/And3rsL/Deebot-for-hassio

it seems they can all list the vacuum - but none can control it.

**Configuration.yaml (Remember to delete your credentials)**
```
deebot:
  username: !secret ecovacs_user
  password: !secret ecovacs_pass
  country: at
  continent: ww/eu
  deviceid:
    - !secret ecovacs_deviceid
```

**Screenshots**

**System Informations:**
 - Device: Deebot OZMO Slim 10
 - Home Assistant Version: 2021.1.4
 - Hardware: NAS (Synology x86)
 - Home Assistant Installation: Linux/Docker

**Additional context**

**Logs**

```
2021-01-23 17:57:27 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall vacuum.locate (c:xxxxx): entity_id=['vacuum.staubi']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1461, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 610, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 283, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 323, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/deebot/vacuum.py", line 230, in device_state_attributes
    data['status'] = STATE_CODE_TO_STATE[self.device.vacuum_status]
KeyError: None
```

**Comment by And3rsL** [comment]
Can you try again with version 2.0.0?

**Comment by h4de5** [comment]
just tested it again with the current code:

```
2021-01-27 12:15:56 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for deebot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-01-27 12:16:10 WARNING (MainThread) [homeassistant.components.vacuum] Setup of vacuum platform deebot is taking over 10 seconds.
2021-01-27 12:16:45 WARNING (schedule_thread_components) [deebotozmo] No last clean image found
2021-01-27 12:17:00 ERROR (MainThread) [homeassistant.components.vacuum] Setup of platform deebot is taking longer than 60 seconds. Startup will proceed without waiting any longer.
2021-01-27 12:18:52 WARNING (schedule_thread_components) [deebotozmo] No last clean image found
```

tested it with `continent: ww` and `eu` - the vacuum is shown with the correct name, but is listed as unavailable in HA.

the following domains has been checked by the integration:

```
portal-eu.ecouser.net
gl-at-openapi.ecovacs.com
gl-at-api.ecovacs.com
portal-ww.ecouser.net
```

**Comment by And3rsL** [comment]
Does your robot show clean history with images?

**Comment by h4de5** [comment]
no. in the app i just see plain history and how much it cleaned.

**Comment by edenhaus** [comment]
> Any news to this?

Andrea and I, we have only the Ozmo 950 and so you must provide us with information. Also we can only solve this issue with your help. 

Can you please provide us with debug logs. We probably need to disable live map as your robot is not supporting it

**Comment by edenhaus** [comment]
@mrbungle64 Thanks for the information :)

Our component supports only MQTT/JSON, which means your robot is not supported.
